// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzzestgyrqnpfyrwqqww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6emVzdGd5cnFucGZ5cndxcXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NzEwMjcsImV4cCI6MjA3NzE0NzAyN30.FxDx6jlQLEkxiQVUKdno-FOK08G-WWjm6QKWXd_LFi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});